using System.Reflection;
using System.Text;
using Basic.Reference.Assemblies;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Harp.Generators.Tests;

internal static class CompilerTestHelper
{
    const string GeneratedElement = "<auto-generated>";
    const string GeneratedElementEnd = "</auto-generated>";

    public static void CompileFromSource(params string[] code)
    {
        Compile(code);
    }

    public static Assembly CompileAndLoadFromSource(params string[] code)
    {
        var bytes = Compile(code);
        return Assembly.Load(bytes);
    }

    static byte[] Compile(string[] code)
    {
        var options = CSharpParseOptions.Default;
        var syntaxTrees = Array.ConvertAll(code, text => CSharpSyntaxTree.ParseText(StripGeneratedHeader(text), options));
        var serializerDependencies = new[]
        {
            typeof(YamlDotNet.Core.Parser).Assembly.Location,
            typeof(Newtonsoft.Json.JsonConvert).Assembly.Location,
            typeof(System.Reactive.Linq.Observable).Assembly.Location,
            typeof(Bonsai.Combinator).Assembly.Location,
            typeof(Bonsai.Harp.HarpMessage).Assembly.Location,
            typeof(Bonsai.IO.FileSink).Assembly.Location
        };
        var assemblyReferences = serializerDependencies.Select(path => MetadataReference.CreateFromFile(path)).ToList();
        assemblyReferences.AddRange(Net80.References.All);

        var compilation = CSharpCompilation.Create(
            nameof(CompilerTestHelper),
            syntaxTrees: syntaxTrees,
            references: assemblyReferences,
            options: new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                allowUnsafe: true,
                nullableContextOptions: NullableContextOptions.Enable));
        using var memoryStream = new MemoryStream();
        var result = compilation.Emit(memoryStream);
        if (!result.Success)
        {
            var errorMessages = (from diagnostic in result.Diagnostics
                                 where diagnostic.IsWarningAsError || diagnostic.Severity == DiagnosticSeverity.Error
                                 select $"{diagnostic.Id}: {diagnostic.GetMessage()}")
                                .ToList();
            Assert.Fail(string.Join(Environment.NewLine, errorMessages));
        }

        AssertNoNullableWarnings(result.Diagnostics);
        return memoryStream.ToArray();
    }

    static string StripGeneratedHeader(string code)
    {
        var element = code.IndexOf(GeneratedElement, StringComparison.Ordinal);
        if (element < 0)
            return code;

        var elementEnd = code.IndexOf(GeneratedElementEnd, element, StringComparison.Ordinal);
        var elementLine = elementEnd < 0 ? -1 : code.IndexOf('\n', elementEnd);
        var headerEnd = elementLine < 0 ? -1 : code.IndexOf('\n', elementLine + 1);
        if (headerEnd < 0)
        {
            Assert.Fail("The auto-generated header was not recognized, so nullable warnings would be suppressed.");
        }

        return code.Substring(headerEnd + 1);
    }

    static void AssertNoNullableWarnings(IEnumerable<Diagnostic> diagnostics)
    {
        var warnings = (from diagnostic in diagnostics
                        where diagnostic.Id.StartsWith("CS86", StringComparison.Ordinal)
                           || diagnostic.Id.StartsWith("CS87", StringComparison.Ordinal)
                        select $"{diagnostic.Id}: {diagnostic.GetMessage()}")
                       .ToList();
        if (warnings.Count > 0)
        {
            var errorLog = new StringBuilder();
            errorLog.AppendLine("The compiled sources report nullable warnings:");
            foreach (var warning in warnings)
                errorLog.AppendLine(warning);
            Assert.Fail(errorLog.ToString());
        }
    }
}
